name: jobAB

on: [push]

jobs:
  jobA:
    runs-on: ubuntu-latest
    steps:
      - name: cmdline01
        run: echo This is from cmdline01.
  jobB:
    runs-on: macos-latest
    needs: [jobA]
    steps:
      - name: cmdline02
        run: echo This is from cmdline02.
