name: hello

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Step-before-checkout
      run: ls -la
    - name: Step-checkout
      uses: actions/checkout@v1
    - name: Step-after-checkout
      run: ls -la
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Newman Action
      uses: anthonyvscode/newman-action@v1
      with:
        collection: echo.json
        reporters: cli,junit
    - name: Copy-result-to-reports-dir
      run: cp -r newman/ reports
    - name: Step-after-newman
      run: ls -la *
      
    - run: npm ci                   # install packages
    - run: npm test                 # run tests (configured to use jest-junit reporter)

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: JEST Tests            # Name of the check run which will be created
        path: reports/jest-*.xml    # Path to test results
        reporter: jest-junit        # Format of test results
    - name: Upload-artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: files
        path: .
    
