name: hello

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Step-before-checkout
      run: ls -la
    - name: Step-checkout
      uses: actions/checkout@v1
    - name: Step-after-checkout
      run: ls -la
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Newman Action
      uses: matt-ball/newman-action@v0.2.4
      with:
        collection: echo-test.json
    - name: Step-after-newman
      run: ls -la

    
