name: hello

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Step-before-checkout
      run: ls -la
    - name: Step-checkout
      uses: actions/checkout@v1
    - name: Step-after-checkout
      run: ls -la
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Newman Action
      # You may pin to the exact commit or the version.
      # uses: matt-ball/newman-action@0659e9b8d056c0d03d94e1dbfce380512088b566
      uses: matt-ball/newman-action@v0.2.4
      with:
        # Collection to use
        collection: abc.json

    
